### ISSUE TITLE
Logo image not served by Cypres

### ISSUE THREAD

**Issue by bahmutov** [bahmutov/vue-cli-and-cypress#1]
When running `app-spec.js` the logo is bundled through webpack proxy, but Cypress does not have this feature.

<img width="1074" alt="screen shot 2017-12-27 at 12 27 58 am" src="https://user-images.githubusercontent.com/2212006/34371653-fec869cc-ea9c-11e7-8071-f96db0468eb0.png">

Cypress 1.4.1

**Comment by bahmutov** [comment]
work around

**Comment by shrinidhimayya** [comment]
@bahmutov  how to serve static assets from public folder using cypress 13.
using svelte framework and bundler as webpack
